# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluent-plugin-s3}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = %q{2011-09-27}
  s.email = %q{frsyuki@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog",
     "README.rdoc"
  ]
  s.files = [
    "AUTHORS",
     "Rakefile",
     "VERSION",
     "lib/fluent/plugin/out_s3.rb"
  ]
  s.homepage = %q{http://fluent.github.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Amazon S3 output plugin for Fluent event collector}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fluent>, ["~> 0.9.14"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 1.1.3"])
    else
      s.add_dependency(%q<fluent>, ["~> 0.9.14"])
      s.add_dependency(%q<aws-sdk>, ["~> 1.1.3"])
    end
  else
    s.add_dependency(%q<fluent>, ["~> 0.9.14"])
    s.add_dependency(%q<aws-sdk>, ["~> 1.1.3"])
  end
end

