name: "Mark or close stale issues and PRs"
on:
  schedule:
  - cron: "00 10 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 7
        stale-issue-message: "This issue has been automatically marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this issue will be closed in 7 days"
        stale-pr-message: "This PR has been automatically marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this PR will be closed in 7 days"
        close-issue-message: "This issue was automatically closed because of stale in 7 days"
        close-pr-message: "This PR was automatically closed because of stale in 7 days"
        stale-pr-label: "stale"
        stale-issue-label: "stale"
        exempt-issue-labels: "waiting-for-triage,bug,help wanted,enhancement"
        exempt-pr-labels: "waiting-for-triage,bug,help wanted,enhancement"
        exempt-all-assignees: true
        exempt-all-milestones: true
